import { AnimatePresence, motion } from "framer-motion";
import { Activity } from "lucide-react";
import type { FriendlyStatus } from "../types";
import { cn } from "../lib/utils";

interface StatusTickerProps {
  // The latest patient-friendly one-liner generated by the Featherless
  // translator. We intentionally DO NOT fall back to raw logs — those contain
  // technical noise ("HTTP GET attempt 1/3…") that patients shouldn't see.
  // Before the first friendly_status arrives, we show a gentle placeholder.
  friendlyStatus: FriendlyStatus | null;
  running: boolean;
}

export function StatusTicker({
  friendlyStatus,
  running,
}: StatusTickerProps) {
  // While the pipeline is running but the first LLM rewrite hasn't landed
  // yet, show a calm placeholder so the ticker never flashes jargon.
  const showIdleRunning = running && !friendlyStatus;
  const showIdle = !running && !friendlyStatus;

  return (
    <div className="relative overflow-hidden rounded-2xl border border-border bg-card p-5 shadow-soft sm:p-6">
      <div className="flex items-center gap-3">
        <span
          className={cn(
            "h-2.5 w-2.5 shrink-0 rounded-full",
            running ? "bg-emerald-500 animate-pulse-ring" : "bg-slate-300"
          )}
        />

        <div className="relative min-h-[1.25rem] flex-1 overflow-hidden">
          <AnimatePresence mode="popLayout" initial={false}>
            {friendlyStatus ? (
              <motion.div
                key={`f-${friendlyStatus.id}`}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.22, ease: "easeOut" }}
                className="flex items-center"
              >
                <span
                  className="truncate text-sm text-foreground"
                  title={friendlyStatus.message}
                >
                  {friendlyStatus.message}
                </span>
              </motion.div>
            ) : showIdleRunning ? (
              <motion.div
                key="warming"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="flex items-center gap-2 text-sm text-muted-foreground"
              >
                <span>Getting your search started…</span>
              </motion.div>
            ) : showIdle ? (
              <motion.div
                key="idle"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="flex items-center gap-2 text-sm text-muted-foreground"
              >
                <Activity className="h-4 w-4" />
                <span>Idle — click Find Trials to begin.</span>
              </motion.div>
            ) : null}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
