import { AnimatePresence, motion } from "framer-motion";
import { Activity } from "lucide-react";
import type { FriendlyStatus, LogKind, LogLine } from "../types";
import { cn, formatTimestamp } from "../lib/utils";

interface StatusTickerProps {
  logs: LogLine[];
  // The latest patient-friendly one-liner generated by the Featherless
  // translator. When present, we render this INSTEAD of the raw log line so
  // patients see plain language. Falls back to the most recent raw log until
  // the first friendly_status event arrives.
  friendlyStatus: FriendlyStatus | null;
  running: boolean;
}

// Color chip per log "kind" — matches the step card colors so the eye can
// track which step the current event belongs to.
const CHIP_CLASSES: Record<LogKind, string> = {
  "step-1": "bg-emerald-100 text-emerald-700 ring-emerald-200",
  "step-2": "bg-amber-100 text-amber-800 ring-amber-200",
  "step-3": "bg-orange-100 text-orange-700 ring-orange-200",
  "step-4": "bg-pink-100 text-pink-700 ring-pink-200",
  error: "bg-red-100 text-red-700 ring-red-200",
  system: "bg-violet-100 text-violet-700 ring-violet-200",
};

const CHIP_LABEL: Record<LogKind, string> = {
  "step-1": "Step 1",
  "step-2": "Step 2",
  "step-3": "Step 3",
  "step-4": "Step 4",
  error: "Error",
  system: "System",
};

// Display shape shared by friendly-status and raw-log fallbacks so the
// render path stays a single branch below.
interface TickerItem {
  id: number | string;
  kind: LogKind;
  ts: number;
  message: string;
}

export function StatusTicker({
  logs,
  friendlyStatus,
  running,
}: StatusTickerProps) {
  // Prefer the patient-friendly line. If none has arrived yet (e.g. the very
  // first 1–2 seconds of a run, or Featherless is unavailable), fall back
  // to the most recent raw log so the ticker never goes silent.
  let item: TickerItem | null = null;
  if (friendlyStatus) {
    item = {
      id: `f-${friendlyStatus.id}`,
      kind: friendlyStatus.kind,
      ts: friendlyStatus.ts,
      message: friendlyStatus.message,
    };
  } else if (logs.length > 0) {
    const latest = logs[logs.length - 1];
    item = {
      id: `l-${latest.id}`,
      kind: latest.kind,
      ts: latest.ts,
      message: latest.message,
    };
  }

  return (
    <div className="relative overflow-hidden rounded-2xl border border-border bg-card p-5 shadow-soft sm:p-6">
      <div className="flex items-center gap-3">
        <span
          className={cn(
            "h-2.5 w-2.5 shrink-0 rounded-full",
            running ? "bg-emerald-500 animate-pulse-ring" : "bg-slate-300"
          )}
        />

        <div className="relative min-h-[1.25rem] flex-1 overflow-hidden">
          <AnimatePresence mode="popLayout" initial={false}>
            {item ? (
              <motion.div
                key={item.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: -10 }}
                transition={{ duration: 0.22, ease: "easeOut" }}
                className="flex items-center gap-2.5"
              >
                <span
                  className={cn(
                    "inline-flex shrink-0 items-center rounded-md px-1.5 py-0.5 text-[10px] font-bold uppercase tracking-[0.06em] ring-1 ring-inset",
                    CHIP_CLASSES[item.kind]
                  )}
                >
                  {CHIP_LABEL[item.kind]}
                </span>
                <span className="shrink-0 font-mono text-[11px] text-muted-foreground">
                  {formatTimestamp(item.ts)}
                </span>
                <span
                  className="truncate text-sm text-foreground"
                  title={item.message}
                >
                  {item.message}
                </span>
              </motion.div>
            ) : (
              <motion.div
                key="idle"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="flex items-center gap-2 text-sm text-muted-foreground"
              >
                <Activity className="h-4 w-4" />
                <span>Idle — click Find Trials to begin.</span>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
