export interface Contact {
  name: string;
  role: string;
  phone: string;
  email: string;
}

export interface GeoPoint {
  lat: number;
  lng: number;
}

export interface Trial {
  nct_id?: string | null;
  nct_url?: string;
  mayo_url?: string;
  title: string;
  eligibility_criteria?: string;
  location?: string;
  sites_count?: number;
  phase?: string;
  summary?: string;
  source: string;
  contacts?: Contact[];
  /** Lat/lng of the "best" recruiting site, when the source provides one. */
  geo?: GeoPoint | null;
}

export interface Score {
  trial_index: number;
  match_score: number | null;
  match_level: "high" | "medium" | "low" | string;
  /** One-sentence plain-English reason for this score, generated by Featherless. */
  score_reason?: string;
  rationale: string;
  key_eligibility_factors: string[];
  potential_exclusions: string[];
  plain_english_summary: string;
}

export interface ScoredEntry {
  trial: Trial;
  score: Score;
}

export type StepStatus = "idle" | "pending" | "running" | "complete" | "error";

export interface StepState {
  step: 1 | 2 | 3 | 4;
  status: StepStatus;
  title: string;
  summary: string;
}

export type LogKind = "step-1" | "step-2" | "step-3" | "step-4" | "error" | "system";

export interface LogLine {
  id: number;
  step: number | null;
  message: string;
  ts: number;
  kind: LogKind;
}

export interface LogEvent {
  type: "log";
  step: number | null;
  message: string;
  ts: number;
}

export interface StepUpdateEvent {
  type: "step_update";
  step: 1 | 2 | 3 | 4;
  status: StepStatus;
  title?: string;
  summary?: string;
  ts: number;
}

export interface TrialAddedEvent {
  type: "trial_added";
  trial: Trial;
  ts: number;
}

// Sent once near the start of a pipeline run with the patient's resolved
// lat/lng (from their ZIP). The UI uses this as the anchor point for the
// "sort by closest/farthest" feature on the Location column.
export interface PatientGeoEvent {
  type: "patient_geo";
  geo: GeoPoint | null;
  ts: number;
}

export interface ScoredAddedEvent {
  type: "scored_added";
  entry: ScoredEntry;
  ts: number;
}

// A patient-friendly one-liner produced by the Featherless translator. These
// replace the raw technical log line in the live status ticker so patients
// see plain-language updates ("We're now looking at Mayo Clinic…") instead
// of jargon ("[Step 3] HTTP GET attempt 1/3…").
export interface FriendlyStatusEvent {
  type: "friendly_status";
  step: number | null;
  message: string;
  ts: number;
}

// In-memory shape tracked in useTrialStream for the latest friendly update.
export interface FriendlyStatus {
  id: number;
  step: number | null;
  message: string;
  ts: number;
  kind: LogKind;
}

export interface PipelineResult {
  patient_profile: Record<string, unknown>;
  patient_geo?: GeoPoint | null;
  raw_trials: Trial[];
  scored_trials: ScoredEntry[];
  meta: {
    counts: Record<string, number>;
    errors: string[];
    elapsed_ms: number;
  };
}

export interface ResultEvent {
  type: "result";
  payload: PipelineResult;
}

export interface DoneEvent {
  type: "done";
  ts?: number;
}

export type SSEEvent =
  | LogEvent
  | StepUpdateEvent
  | TrialAddedEvent
  | PatientGeoEvent
  | ScoredAddedEvent
  | FriendlyStatusEvent
  | ResultEvent
  | DoneEvent;

/** Patient profile for trial matching (from Featherless parsing pypdf JSON). */
export interface PatientProfileExtracted {
  summary: string;
  first_name: string | null;
  last_name: string | null;
  email: string | null;
  age: number | null;
  zip_code: string | null;
  diagnosis: string | null;
  cancer_type: string | null;
  stage: string | null;
  biomarkers: Record<string, string>;
  prior_treatments: string[];
  performance_status: string | null;
  comorbidities: string[];
  discuss_with_oncologist: string;
}

/** @deprecated use PatientProfileExtracted */
export type ExtractedProfile = PatientProfileExtracted;

/** Safe summary of pypdf output (no raw page text). */
export interface PdfExtractionSummary {
  format: string | null;
  page_count: number;
  total_text_chars: number;
  chars_per_page: number[];
}

export interface ReadPdfMeta {
  filename: string;
  bytes: number;
  text_chars_extracted: number;
  json_chars_sent_to_model: number;
  json_truncated_for_model: boolean;
}

export interface ReadPdfResponse {
  extracted_profile: PatientProfileExtracted;
  /** Server hint: which fields are still empty and should be collected in the UI. */
  missing_fields?: string[];
  pdf_extraction: PdfExtractionSummary;
  meta: ReadPdfMeta;
}
